Drop table if exists P_ROBEVANS_T.SNEAKERS_SHIPPING_COSTS;

Create table P_ROBEVANS_T.SNEAKERS_SHIPPING_COSTS as

Select ck.ITEM_ID
,ck.TRANSACTION_ID
,cat.CATEG_LVL4_NAME
,ck.GMV_DT
,cal.RETAIL_YEAR
,cal.RETAIL_WEEK
,shp.GSP_IND
,ck.SELLER_ID
,ck.SLR_CNTRY_ID
,ck.BYR_CNTRY_ID
,ck.ITEM_PRICE as item_price_lc
,sum(shp.SHPMT_FEE_LC_AVG_AMT) as SHPMT_FEE_LC_AVG_AMT
,sum(ck.SHIPPING_FEE) as ck_shipping_fee_lc
,sum(ck.TRANS_SHPNG_FEE_AMT) as TRANS_SHPNG_FEE_AMT_LC
,sum(ck.TRANS_HNDLNG_FEE_AMT) as TRANS_HNDLNG_FEE_AMT_LC

From DW_CHECKOUT_TRANS ck
INNER JOIN ACCESS_VIEWS.DW_CAL_DT cal
	on ck.GMV_DT = cal.CAL_DT
	and cal.AGE_FOR_RTL_WEEK_ID between -52 and -1
INNER JOIN ACCESS_VIEWS.DW_CATEGORY_GROUPINGS CAT
	ON ck.LEAF_CATEG_ID = CAT.LEAF_CATEG_ID
	AND cat.site_id = 3
	AND cat.SAP_CATEGORY_ID NOT IN (5,7,41,23,-999)
INNER JOIN ACCESS_VIEWS.SSA_SHPMT_TRANS_FACT shp
	on ck.ITEM_ID = shp.LSTG_ID
	and ck.TRANSACTION_ID = shp.CK_TRANS_ID
	and upper(FREE_SHPNG_YN_IND) = 'N'

WHERE 1=1
and ck.CK_WACKO_YN = 'N'
and ck.SLR_CNTRY_ID = 3
and ck.TRANS_SITE_ID = 3
and cat.categ_lvl4_id in (15709,95672)
and ck.ITEM_PRICE >= 100
and ck.SHIPPING_FEE > 0 

Group by 1,2,3,4,5,6,7,8,9,10,11



;